"""fix typo in amount and logic

Revision ID: 7fa7aa178b1f
Revises: 13247ec46d0c
Create Date: 2026-01-05 18:34:52.242293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa7aa178b1f'
down_revision: Union[str, Sequence[str], None] = '13247ec46d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('order_item', 'amout')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('amout', sa.INTEGER(), nullable=True))
    op.drop_column('order_item', 'amount')
    # ### end Alembic commands ###
